// AUTO-GENERATED by scripts/apply-brand.mjs. Do not edit manually.

export type BrandingConfig = {
  brandKey: string;
  productName: string;
  desktopTitle: string;
  bundleIdentifier: string;
  publisher: string;
  exeName: string;
  localStoragePrefix: string;
  protocolScheme: string;
  assetsDir: string;
};

export const BRANDING: BrandingConfig = {
  "brandKey": "bifclaw",
  "productName": "BifClaw",
  "desktopTitle": "BifClaw",
  "bundleIdentifier": "dev.bifclaw.runtime",
  "publisher": "BifClaw",
  "exeName": "BifClaw",
  "localStoragePrefix": "bifclaw",
  "protocolScheme": "bifclaw",
  "assetsDir": "./assets"
} as const;

export default BRANDING;
