// AUTO-GENERATED by scripts/apply-brand.mjs. Do not edit manually.
#![allow(dead_code)]

pub const BRAND_KEY: &str = "bifclaw";
pub const PRODUCT_NAME: &str = "BifClaw";
pub const DESKTOP_TITLE: &str = "BifClaw";
pub const BUNDLE_IDENTIFIER: &str = "dev.bifclaw.runtime";
pub const PUBLISHER: &str = "BifClaw";
pub const EXE_NAME: &str = "BifClaw";
pub const LOCAL_STORAGE_PREFIX: &str = "bifclaw";
pub const PROTOCOL_SCHEME: &str = "bifclaw";
pub const DEFAULT_RUNTIME_ROOT_DIR_NAME: &str = ".bifclaw";
pub const AUTOSTART_NAME: &str = "dev.bifclaw.runtime";
