// AUTO-GENERATED by scripts/apply-brand.mjs. Do not edit manually.

pub const BRAND_KEY: &str = "workclaw";
pub const PRODUCT_NAME: &str = "WorkClaw";
pub const DESKTOP_TITLE: &str = "WorkClaw";
pub const BUNDLE_IDENTIFIER: &str = "dev.workclaw.runtime";
pub const PUBLISHER: &str = "WorkClaw";
pub const EXE_NAME: &str = "WorkClaw";
pub const LOCAL_STORAGE_PREFIX: &str = "workclaw";
pub const PROTOCOL_SCHEME: &str = "workclaw";
pub const DEFAULT_RUNTIME_ROOT_DIR_NAME: &str = ".workclaw";
pub const AUTOSTART_NAME: &str = "dev.workclaw.runtime";
